steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/kmcc-qc-dashboard/qc-dashboard:$SHORT_SHA'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/kmcc-qc-dashboard/qc-dashboard:latest'
      - '.'
    id: 'build-image'

  # Artifact Registry에 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/kmcc-qc-dashboard/qc-dashboard'
    id: 'push-image'

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qc-dashboard'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/kmcc-qc-dashboard/qc-dashboard:$SHORT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,BIGQUERY_PROJECT_ID=splyquizkm,BIGQUERY_DATASET_ID=KMCC_QC'
    id: 'deploy-cloud-run'

# 빌드 옵션
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'

# 리전 설정
substitutions:
  _REGION: 'asia-northeast3'

# 이미지 저장소
images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/kmcc-qc-dashboard/qc-dashboard:$SHORT_SHA'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/kmcc-qc-dashboard/qc-dashboard:latest'

# 타임아웃
timeout: '1200s'
